### ISSUE TITLE
PT - LLM04 - Missing section of Example Attack Scenarios

### ISSUE THREAD

**Issue by talesh** [talesh/www-project-top-10-for-large-language-model-applications#57]
This is not translated in 7. of the Example attack scenarios:

> such as API limitations. For example, in a recent Sourcegraph security incident, the malicious actor employed a leaked admin access token to alter API rate limits, thereby potentially causing service disruptions by enabling abnormal levels of request volumes.

It is completely missing from the Portuguese translations

Original file:
https://github.com/OWASP/www-project-top-10-for-large-language-model-applications/blob/main/1_1_vulns/LLM04_ModelDoS.md#example-attack-scenarios

Translated file missing the ending of 7. 
https://github.com/talesh/www-project-top-10-for-large-language-model-applications/blob/main/1_1_vulns/pt/LLM04_ModelDoS.md#cen%C3%A1rios-de-ataque-exemplo

**Comment by emmanuelgjr** [comment]
This looks complete, according to the original.
