### ISSUE TITLE
PT - LLM05 - Missing Example Attack Scenario

### ISSUE THREAD

**Issue by talesh** [talesh/www-project-top-10-for-large-language-model-applications#58]
Part of 6 and all of 7 is also missing from LLM05: 

>  An LLM operator changes its T&Cs and Privacy Policy to require an explicit opt out from using application data for model training, leading to the memorization of sensitive data.

This seems to be cut off from a copy/paste

Original file with complete 6. and 7. 
https://github.com/OWASP/www-project-top-10-for-large-language-model-applications/blob/main/1_1_vulns/LLM05_SupplyChainVulnerabilities.md#example-attack-scenarios

Translated file with missing parts:
https://github.com/talesh/www-project-top-10-for-large-language-model-applications/blob/main/1_1_vulns/pt/LLM05_SupplyChainVulnerabilities.md#cen%C3%A1rios-de-ataque-exemplo

**Comment by RubensZimbres** [comment]
The right solution is:

6. Um funcionário comprometido de um fornecedor (desenvolvedor terceirizado, empresa de hospedagem, etc.) exfiltra dados, modelo ou código, roub**ando propriedade intelectual**
7. **Um operador LLM altera seus T&Cs e Política de Privacidade para exigir uma recusa explícita de usar dados de aplicativos para treinamento de modelo, levando à memorização de dados confidenciais.**

There was a missing item also (7).
